### ISSUE TITLE
SOLVED: pip install cashu fails on Mac M1

### ISSUE THREAD

**Issue by SachinMeier** [cashubtc/cashu#65]
OS: `MacOS Monterey 12.6` (M1 chip)
pip --version:  `pip 22.3.1 from ~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pip (python 3.9)`
python --version: `Python 3.9.6`

output of `pip install cashu`:

```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      0.29.2
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            WARNING: The wheel package is not available.
            WARNING: The wheel package is not available.
            WARNING: The wheel package is not available.
            WARNING: The wheel package is not available.
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'bdist_wheel'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pytest-runner
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "~/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['~/.pyenv/versions/3.9.6/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/yb/2yjpdb4s2qq7hdxkkg733x6w0000gp/T/tmpuhmpzya5', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/yb/2yjpdb4s2qq7hdxkkg733x6w0000gp/T/pip-install-_z6n02gh/secp256k1_c7507d2878714c0f954129c77c902f1b/setup.py", line 265, in <module>
          setup(
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/setuptools/dist.py", line 780, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "~/.pyenv/versions/3.9.6/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['~/.pyenv/versions/3.9.6/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/yb/2yjpdb4s2qq7hdxkkg733x6w0000gp/T/tmpuhmpzya5', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by SachinMeier** [comment]
On macOS, you have to run `pip install wheel` and `brew install pkg-config`.
